In [14]:
#Q1. Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

import numpy as np
x=np.random.random((10,1))
print(x)
print("Mean = ",np.mean(x))

[[0.52715481]
 [0.44741105]
 [0.10958653]
 [0.3850531 ]
 [0.01443588]
 [0.04881806]
 [0.05513691]
 [0.24441738]
 [0.45550935]
 [0.43810394]]
Mean =  0.2725627008367349


In [15]:
#Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.

import numpy as np
x=np.random.random((20,1))
print(x)
print("Variance is ",np.var(x))
print("Standard deviationn is ",np.std(x))

[[0.70045287]
 [0.52503636]
 [0.79889   ]
 [0.73137527]
 [0.75036731]
 [0.47346637]
 [0.15121862]
 [0.11818093]
 [0.32408319]
 [0.51607247]
 [0.27449219]
 [0.59135224]
 [0.35130865]
 [0.25941355]
 [0.03901374]
 [0.27819999]
 [0.40886207]
 [0.74936072]
 [0.93143462]
 [0.73524495]]
Variance is  0.06271466064654721
Standard deviationn is  0.25042895329124226


In [20]:
#Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. 
#      Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25).
#      Using basic numpy math functions only find the sum of all the elements of the new matrix.

import numpy as np
A=np.random.random((10,20))
B=np.random.random((20,25))
C=np.matmul(A,B)
print(C)
print("Shape is ",C.shape)
print("Sum of all elements : ",np.sum(C))

[[4.37033107 4.63406365 3.31574127 5.05631052 4.12840391 3.96795151
  3.56492903 3.4442461  4.5828631  4.03102697 3.97262701 5.0465925
  4.71954301 2.46474901 4.3687352  3.21167343 4.71233503 3.29191432
  3.64448228 4.62254293 4.85824596 3.29834103 3.10543957 4.56511557
  4.72667687]
 [4.9777214  4.86041389 3.88309792 5.00485454 4.42944615 4.03908754
  4.86531494 4.39904234 5.00888459 4.83904925 4.64876963 4.94583089
  5.55180677 3.51128969 4.70166574 3.87007905 5.83876391 3.99995334
  4.56224315 4.34207605 4.7901433  4.20519659 3.02539161 5.18104406
  5.00115495]
 [3.66156732 3.50467009 3.67774273 4.58325625 3.94631727 4.3578711
  5.20305065 4.61969664 3.9390799  3.74384543 3.6835258  4.38251354
  4.60318357 3.31781352 4.38837733 3.35429775 4.20754779 3.09541163
  4.51891319 4.00959411 4.40098437 3.16263664 3.38819797 4.9458298
  3.57855919]
 [5.07802524 5.41810695 4.23305848 5.93649703 5.10896433 5.5032159
  5.49914579 5.21069661 5.64114602 5.45433887 4.55154191 5.9973427
  5.6630653

In [27]:
#Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A. 

import numpy as np

A=np.random.random((10,1))
print(A)

def fun(A):
    B=np.zeros((10,1))
    for i in range(10):
        x=1 / (1 + np.exp(-A[i]))
        B[i]=x
    print(B)
print("- "*20)
fun(A)
        
     
    

[[0.81316517]
 [0.14087069]
 [0.54830041]
 [0.55302147]
 [0.29707489]
 [0.67327008]
 [0.69069252]
 [0.6936543 ]
 [0.515974  ]
 [0.39525535]]
- - - - - - - - - - - - - - - - - - - - 
[[0.69278357]
 [0.53515955]
 [0.63374118]
 [0.63483631]
 [0.57372729]
 [0.662235  ]
 [0.66612096]
 [0.66677935]
 [0.62620587]
 [0.59754718]]
